//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/_Inputs/InputMaster.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMaster : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMaster()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMaster"",
    ""maps"": [
        {
            ""name"": ""Players"",
            ""id"": ""d60d2d99-1629-41c0-85f0-a4715f1e12e5"",
            ""actions"": [
                {
                    ""name"": ""P1_Move"",
                    ""type"": ""Value"",
                    ""id"": ""f00ace12-b492-4882-8130-b761ce066b09"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""InvertVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""P2_Move"",
                    ""type"": ""Value"",
                    ""id"": ""a983ce62-42ab-4bd3-a5b2-febe9223c3b9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""InvertVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""P1_LeftButton"",
                    ""type"": ""Button"",
                    ""id"": ""a4056034-7def-4f32-a7d0-e367f3156e23"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2_LeftButton"",
                    ""type"": ""Button"",
                    ""id"": ""44e10482-1be0-4f78-bebe-98e3caab76ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1_RightButton"",
                    ""type"": ""Button"",
                    ""id"": ""7ff6e251-53d3-4852-9679-5c16e639ea70"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2_RightButton"",
                    ""type"": ""Button"",
                    ""id"": ""5d65a26f-92fa-4c6d-9bd0-96f41d386831"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1_UpButton"",
                    ""type"": ""Button"",
                    ""id"": ""7c697f19-578f-4c43-bab9-fb2f3a8d69c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2_UpButton"",
                    ""type"": ""Button"",
                    ""id"": ""72078568-7dec-4d60-878d-f7ca353d7df0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1_DownButton"",
                    ""type"": ""Button"",
                    ""id"": ""d417c95f-8e16-4557-9c77-a58a8aae7af6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2_DownButton"",
                    ""type"": ""Button"",
                    ""id"": ""da34284e-c2d9-4563-8e16-2f03bda065af"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e0e0cb63-7d01-4f32-b87b-7dc0026312b2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f4984bd6-c6eb-425b-b476-6c8b59fc0c44"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""379d413b-7b3c-48e4-adba-fb6fbe462b6a"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e9150202-6e6f-4edb-a3a8-b098f33fabd2"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""873622f1-c5d2-48be-bad4-c4c159c44e55"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""b273d4ed-25f9-4ab7-ae4a-ad3643619997"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6954cdfb-dcc0-4a2a-93f2-97402ee94585"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4cfe929b-c9fd-4f22-a8ae-223922ccd4e9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""50cb0425-3560-41f7-97f4-e735c5d16408"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""41f9d23e-7b01-4531-b9b3-b6cff631a967"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a472b67a-0097-4945-b44a-fd1ecd259a2c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f0f782ba-6e18-49e8-b69d-393ce23d02a5"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""774340a7-3085-408c-ab3e-ed943a6320be"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e0d04dc1-ce75-4f15-bb1d-82b60681df7e"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f83fddf8-0d05-4c4e-bcee-6044e2418237"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""de9ca8c8-38c8-49a2-8998-1b7043a0d62a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5ecb28e5-c47e-4e36-ba98-02e3ae3735fe"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d93fdf08-6e1a-462b-a685-a15c05d9f24e"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""89fdc1fa-fa3d-429a-bf9c-71adac989973"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""92093286-d43f-415d-a994-eea482a9a472"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""00d678f6-ef5b-4a6f-9441-7e7c7677c27a"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_LeftButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b18b90d-8f04-49ce-b9bb-de90127b61e1"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_LeftButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca58e5bf-7363-4c33-9c16-e0f3d41dfbc1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_LeftButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb01002c-3841-44dd-ae91-909892311cd9"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_LeftButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fe4a51f-1004-4fb0-8d68-11613914c8be"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_RightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80cc2113-4f28-49d1-a307-7eadffbdc66e"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_RightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""493bda37-1209-40a8-97fc-a10df4dbdcdd"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_RightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3fdc3e0-a147-43b6-9a73-18d0484020f6"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_RightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58468f79-3a74-4d87-9373-4d4a1c2a27d3"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_UpButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20b2d060-081d-46dc-abb9-6f6a8ce9ae43"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_UpButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d21e64d-4d73-4a72-9c15-025f2ea10f83"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_UpButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""485b54cb-9b22-418e-85d2-6a2fba3cdcb7"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_UpButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a36093c-8a79-401f-9c8e-917539715dd8"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_DownButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a622e5cd-d76b-41ce-b0e8-6c65de000fd3"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_DownButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46c50250-135a-4dfc-8b7a-f5e316551155"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_DownButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93cc516a-2cfd-4b2a-b966-7179df967337"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_DownButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Players
        m_Players = asset.FindActionMap("Players", throwIfNotFound: true);
        m_Players_P1_Move = m_Players.FindAction("P1_Move", throwIfNotFound: true);
        m_Players_P2_Move = m_Players.FindAction("P2_Move", throwIfNotFound: true);
        m_Players_P1_LeftButton = m_Players.FindAction("P1_LeftButton", throwIfNotFound: true);
        m_Players_P2_LeftButton = m_Players.FindAction("P2_LeftButton", throwIfNotFound: true);
        m_Players_P1_RightButton = m_Players.FindAction("P1_RightButton", throwIfNotFound: true);
        m_Players_P2_RightButton = m_Players.FindAction("P2_RightButton", throwIfNotFound: true);
        m_Players_P1_UpButton = m_Players.FindAction("P1_UpButton", throwIfNotFound: true);
        m_Players_P2_UpButton = m_Players.FindAction("P2_UpButton", throwIfNotFound: true);
        m_Players_P1_DownButton = m_Players.FindAction("P1_DownButton", throwIfNotFound: true);
        m_Players_P2_DownButton = m_Players.FindAction("P2_DownButton", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Players
    private readonly InputActionMap m_Players;
    private IPlayersActions m_PlayersActionsCallbackInterface;
    private readonly InputAction m_Players_P1_Move;
    private readonly InputAction m_Players_P2_Move;
    private readonly InputAction m_Players_P1_LeftButton;
    private readonly InputAction m_Players_P2_LeftButton;
    private readonly InputAction m_Players_P1_RightButton;
    private readonly InputAction m_Players_P2_RightButton;
    private readonly InputAction m_Players_P1_UpButton;
    private readonly InputAction m_Players_P2_UpButton;
    private readonly InputAction m_Players_P1_DownButton;
    private readonly InputAction m_Players_P2_DownButton;
    public struct PlayersActions
    {
        private @InputMaster m_Wrapper;
        public PlayersActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @P1_Move => m_Wrapper.m_Players_P1_Move;
        public InputAction @P2_Move => m_Wrapper.m_Players_P2_Move;
        public InputAction @P1_LeftButton => m_Wrapper.m_Players_P1_LeftButton;
        public InputAction @P2_LeftButton => m_Wrapper.m_Players_P2_LeftButton;
        public InputAction @P1_RightButton => m_Wrapper.m_Players_P1_RightButton;
        public InputAction @P2_RightButton => m_Wrapper.m_Players_P2_RightButton;
        public InputAction @P1_UpButton => m_Wrapper.m_Players_P1_UpButton;
        public InputAction @P2_UpButton => m_Wrapper.m_Players_P2_UpButton;
        public InputAction @P1_DownButton => m_Wrapper.m_Players_P1_DownButton;
        public InputAction @P2_DownButton => m_Wrapper.m_Players_P2_DownButton;
        public InputActionMap Get() { return m_Wrapper.m_Players; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayersActions set) { return set.Get(); }
        public void SetCallbacks(IPlayersActions instance)
        {
            if (m_Wrapper.m_PlayersActionsCallbackInterface != null)
            {
                @P1_Move.started -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP1_Move;
                @P1_Move.performed -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP1_Move;
                @P1_Move.canceled -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP1_Move;
                @P2_Move.started -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP2_Move;
                @P2_Move.performed -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP2_Move;
                @P2_Move.canceled -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP2_Move;
                @P1_LeftButton.started -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP1_LeftButton;
                @P1_LeftButton.performed -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP1_LeftButton;
                @P1_LeftButton.canceled -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP1_LeftButton;
                @P2_LeftButton.started -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP2_LeftButton;
                @P2_LeftButton.performed -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP2_LeftButton;
                @P2_LeftButton.canceled -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP2_LeftButton;
                @P1_RightButton.started -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP1_RightButton;
                @P1_RightButton.performed -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP1_RightButton;
                @P1_RightButton.canceled -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP1_RightButton;
                @P2_RightButton.started -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP2_RightButton;
                @P2_RightButton.performed -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP2_RightButton;
                @P2_RightButton.canceled -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP2_RightButton;
                @P1_UpButton.started -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP1_UpButton;
                @P1_UpButton.performed -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP1_UpButton;
                @P1_UpButton.canceled -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP1_UpButton;
                @P2_UpButton.started -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP2_UpButton;
                @P2_UpButton.performed -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP2_UpButton;
                @P2_UpButton.canceled -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP2_UpButton;
                @P1_DownButton.started -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP1_DownButton;
                @P1_DownButton.performed -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP1_DownButton;
                @P1_DownButton.canceled -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP1_DownButton;
                @P2_DownButton.started -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP2_DownButton;
                @P2_DownButton.performed -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP2_DownButton;
                @P2_DownButton.canceled -= m_Wrapper.m_PlayersActionsCallbackInterface.OnP2_DownButton;
            }
            m_Wrapper.m_PlayersActionsCallbackInterface = instance;
            if (instance != null)
            {
                @P1_Move.started += instance.OnP1_Move;
                @P1_Move.performed += instance.OnP1_Move;
                @P1_Move.canceled += instance.OnP1_Move;
                @P2_Move.started += instance.OnP2_Move;
                @P2_Move.performed += instance.OnP2_Move;
                @P2_Move.canceled += instance.OnP2_Move;
                @P1_LeftButton.started += instance.OnP1_LeftButton;
                @P1_LeftButton.performed += instance.OnP1_LeftButton;
                @P1_LeftButton.canceled += instance.OnP1_LeftButton;
                @P2_LeftButton.started += instance.OnP2_LeftButton;
                @P2_LeftButton.performed += instance.OnP2_LeftButton;
                @P2_LeftButton.canceled += instance.OnP2_LeftButton;
                @P1_RightButton.started += instance.OnP1_RightButton;
                @P1_RightButton.performed += instance.OnP1_RightButton;
                @P1_RightButton.canceled += instance.OnP1_RightButton;
                @P2_RightButton.started += instance.OnP2_RightButton;
                @P2_RightButton.performed += instance.OnP2_RightButton;
                @P2_RightButton.canceled += instance.OnP2_RightButton;
                @P1_UpButton.started += instance.OnP1_UpButton;
                @P1_UpButton.performed += instance.OnP1_UpButton;
                @P1_UpButton.canceled += instance.OnP1_UpButton;
                @P2_UpButton.started += instance.OnP2_UpButton;
                @P2_UpButton.performed += instance.OnP2_UpButton;
                @P2_UpButton.canceled += instance.OnP2_UpButton;
                @P1_DownButton.started += instance.OnP1_DownButton;
                @P1_DownButton.performed += instance.OnP1_DownButton;
                @P1_DownButton.canceled += instance.OnP1_DownButton;
                @P2_DownButton.started += instance.OnP2_DownButton;
                @P2_DownButton.performed += instance.OnP2_DownButton;
                @P2_DownButton.canceled += instance.OnP2_DownButton;
            }
        }
    }
    public PlayersActions @Players => new PlayersActions(this);
    public interface IPlayersActions
    {
        void OnP1_Move(InputAction.CallbackContext context);
        void OnP2_Move(InputAction.CallbackContext context);
        void OnP1_LeftButton(InputAction.CallbackContext context);
        void OnP2_LeftButton(InputAction.CallbackContext context);
        void OnP1_RightButton(InputAction.CallbackContext context);
        void OnP2_RightButton(InputAction.CallbackContext context);
        void OnP1_UpButton(InputAction.CallbackContext context);
        void OnP2_UpButton(InputAction.CallbackContext context);
        void OnP1_DownButton(InputAction.CallbackContext context);
        void OnP2_DownButton(InputAction.CallbackContext context);
    }
}
